version: 2 
jobs: 
  build: 
    docker: 
      - image: circleci/ruby:2.6.5-stretch
        environment: 
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - chelsea-bundle-v2-{{ checksum "Gemfile.lock" }}
            - chelsea-bundle-v2-
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install
      - save_cache:
          key: chelsea-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml
                            
      - store_test_results:
          path: test_results
